FROM openjdk:8u131-jdk-alpine

VOLUME /tmp

ADD target/model-training-service-1.0.0.war model-training-service.war

ENV JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=38787"

CMD java $JAVA_OPTS -jar /model-training-service.war --spring.profiles.active=docker
